// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyByKO2Y9eZ6No2IwBunr7wokhq-mPiYpVU',
    appId: '1:776776060647:web:7a91ac918247ae97d39c42',
    messagingSenderId: '776776060647',
    projectId: 'portfolio-38486',
    authDomain: 'portfolio-38486.firebaseapp.com',
    storageBucket: 'portfolio-38486.appspot.com',
    measurementId: 'G-0CBB2HHRT0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDMlHkGyDRnHg7s1aB3Kd-dY6w9XbPAi6w',
    appId: '1:776776060647:android:06b11e5f28ba3e7dd39c42',
    messagingSenderId: '776776060647',
    projectId: 'portfolio-38486',
    storageBucket: 'portfolio-38486.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_z1Pu3CSnGuGGUcH3gQC9L6otrX8IAos',
    appId: '1:776776060647:ios:84f21fd87469c120d39c42',
    messagingSenderId: '776776060647',
    projectId: 'portfolio-38486',
    storageBucket: 'portfolio-38486.appspot.com',
    iosBundleId: 'com.example.csvSpreadSheetsDemo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA_z1Pu3CSnGuGGUcH3gQC9L6otrX8IAos',
    appId: '1:776776060647:ios:84f21fd87469c120d39c42',
    messagingSenderId: '776776060647',
    projectId: 'portfolio-38486',
    storageBucket: 'portfolio-38486.appspot.com',
    iosBundleId: 'com.example.csvSpreadSheetsDemo',
  );
}
